### ISSUE TITLE
Have a blocking variant

### ISSUE THREAD

**Issue by piegamesde** [agerasev/ringbuf#12]
This crate is non-blocking: when the buffer is full/empty, it returns `Err(WouldBlock)`. I'd like to have an option with which the buffer blocks until more data/space is available. I can emulate this from the outside, but only with busy waiting, which I'd like to avoid.

**Comment by agerasev** [comment]
Hi, thank you for your proposal! But this crate is designed to be as simple as possible, and introducing blocking variant of ring buffer would make it more complicated. Also it cannot be done without `std` while current implementation has almost full `no_std` support.

I believe the better solution is to make a separate crate based on `ringbuf` with blocking io support. Blocking without CPU consuming could be done using [`std::sync::Condvar`](https://doc.rust-lang.org/stable/std/sync/struct.Condvar.html).

**Comment by kyrias** [comment]
Hey,

Just noticed that you've started working on a blocking wrapper for `ringbuf` which is cool.  How's that work going, and how close do you think you might be to having something ready for a stable release?
