### ISSUE TITLE
Overwriting mode

### ISSUE THREAD

**Issue by Zagitta** [agerasev/ringbuf#13]
Hello,

Would it be possible to introduce an overwriting mode where if the consumer gets too far behind it'll simply lose those unhandled values?

Thanks in advance

**Comment by agerasev** [comment]
Hello,

Sorry for such a late answer. 

I've already considered the possibility of overwriting mode (see https://github.com/agerasev/ringbuf/issues/5#issuecomment-631969268), but I believe it will require a significant complication of the implementation.

Imagine that consumer begins to read an element and at this time the producer pushes a new element at the place of element being read. To avoid this situation we may:

1. Make the ring buffer blocking, but in this case this crate will lose one of its main feature. And this could be easily implemented from the outside of the crate by sharing consumer using mutex. 
2. Allow the producer's push to be failed when element is being read by consumer at the same time. But in this case the producer still have to wait for arbitrary time to push the element. Is this behavior suitable for your needs?

Anyway, thank your for your feature request!
