### ISSUE TITLE
Feature request: HeapRb fallible allocation

### ISSUE THREAD

**Issue by schurwanzn-stabl** [agerasev/ringbuf#24]
Currently `HeapRb::new` uses `Vec::resize_with`, which will panic if an allocation fails.

I propose adding a second function `HeapRb::try_new` which will return `Result<Self, std::collections::TryReserveError>` and uses the same logic as `HeapRb::new` but additionally calls `Vec::try_reserve` before the call to `Vec::resize_with`.

This would be helpful for embedded development where memory is limited and allocations may fail.

**Comment by agerasev** [comment]
Done. Thank you for this feature request!

**Comment by schurwanzn-stabl** [comment]
Awesome! Thank you for implementing it so quickly!
