### ISSUE TITLE
`StaticRb` backed by a static variable?

### ISSUE THREAD

**Issue by scd31** [agerasev/ringbuf#26]
Is something like this safe?

```rust
static mut rb: StaticRb<u8, BUFFER_LEN> = StaticRb::<u8, BUFFER_LEN>::default();
let (mut prod, mut cons) = unsafe { rb.split_ref() };
```

My use-case is I want to have a ring buffer on a no std environment, and I would prefer not to use dynamic allocation if possible. The producer would be used by an interrupt handler, and the consumer used by the main task.

**Comment by agerasev** [comment]
Yes, using statically-allocated ring buffer is safe. But I'd like to add a few points:
1. `StaticRb::default` is not `const` so you may need to use something like `lazy_static` ([example](https://github.com/binp-dev/tornado/blob/develop/source/mcu/user/src/buffers.rs#L46-L47)).
2. But you cannot get mutable reference from `lazy_static` so you need to create producer and consumer manually insted of splitting ([example](https://github.com/binp-dev/tornado/blob/develop/source/mcu/user/src/lib.rs#L29-L30)).

**Comment by scd31** [comment]
Great, thank you!
