### ISSUE TITLE
v0.2.0-rc Async Close Not Waking

### ISSUE THREAD

**Issue by Congyuwang** [agerasev/ringbuf#29]
Seems like the master branch async ringbuf is not yet complete? There is an async [index.rs](https://github.com/agerasev/ringbuf/blob/45cc3a8a01438566869e34b39e74032506353ba6/async/src/index.rs#L24-L28) file not yet included in lib.rs.

Currently, the close() of AsyncProd and AsyncCons does not call `wake()` which can cause some problem. I see that `close()` of `AsyncIndex` calls `wake()`.

[The v0.1.3 Async-Ringbuf](https://github.com/agerasev/async-ringbuf/blob/70a0c8dc5a98b1308491460105c9b033ae587012/src/ring_buffer.rs#L99-L107) also wakes the other on close().

When will this be implemented?

**Comment by Congyuwang** [comment]
My branch migrating from v0.1.3 to v0.2.0-rc.0 has shows some performance bug and occasion lock because the producer `close()` does not wake the consumer.

**Comment by Congyuwang** [comment]
The missing pieces seem to be also `close on drop`, and `wake on close`. Seems like `Drop` is not yet implemented too.

**Comment by Congyuwang** [comment]
#30

**Comment by agerasev** [comment]
Thank you for reporting the issue and investigation you made!

> Seems like the master branch async ringbuf is not yet complete?

It was planned to be final version but I've decided to not to release it yet to give some time to reveal possible bugs (like this one).

>  There is an async [index.rs](https://github.com/agerasev/ringbuf/blob/45cc3a8a01438566869e34b39e74032506353ba6/async/src/index.rs#L24-L28) file not yet included in lib.rs.

`index.rs` is a remnant of previous iteration of rewriting the library, it needs to be removed. Thanks for noticing!
