### ISSUE TITLE
const initializer for `LocalRb<T, [MaybeUninit<T>, N]>`

### ISSUE THREAD

**Issue by anatawa12** [agerasev/ringbuf#35]
I want to use `Mutex<LocalRb<T, [MaybeUninit<T>, N]>>` with static variable but there is no initializer method for `LocalRb<T, [MaybeUninit<T>, N]>`. Could you provide something like `LocalRb<T, [MaybeUninit<T>, N]>::new_const()`?

PS: I found another crate that supports this

**Comment by agerasev** [comment]
Thanks for feature request!
I've added `const fn` constructor for RBs with `Array` storage ([LocalRb](https://docs.rs/ringbuf/0.4.0-rc.4/ringbuf/rb/local/struct.LocalRb.html#method.new), [SharedRb](https://docs.rs/ringbuf/0.4.0-rc.4/ringbuf/rb/shared/struct.SharedRb.html#method.new))
