### ISSUE TITLE
size_of not found in scope in version 0.4.5

### ISSUE THREAD

**Issue by cholcombe973** [agerasev/ringbuf#40]
https://github.com/agerasev/ringbuf/blob/9cf82af66a36942c202b2560bc26bd24da04445a/src/storage.rs#L171
Looks like the compiler can't find this with the latest update. I'll push a fix in a second for it.

**Comment by fcenedes** [comment]
Funny, i've just encounter it :-)

**Comment by cholcombe973** [comment]
I pushed: https://github.com/agerasev/ringbuf/pull/41

**Comment by KKRainbow** [comment]
hope this can me merged. my project must use rustc1.77 for win7 support

**Comment by cholcombe973** [comment]
It's been merged into main :)

**Comment by agerasev** [comment]
Thank you for report! I've published [v0.4.6](https://crates.io/crates/ringbuf/0.4.6) with the fix.
