### ISSUE TITLE
`std::io::Error::new()` allocates

### ISSUE THREAD

**Issue by mgeier** [agerasev/ringbuf#9]
In the `Write` and `Read` implementations, calling `Error::new()` unnecessarily allocates memory (AFAIK):

https://github.com/agerasev/ringbuf/blob/ec34c53c80b3e742ccb66145610b34f615d83606/src/producer.rs#L278-L281

https://github.com/agerasev/ringbuf/blob/ec34c53c80b3e742ccb66145610b34f615d83606/src/consumer.rs#L395-L398

To avoid this, `std::io::ErrorKind::WouldBlock.into()` can be used for error type conversion: https://doc.rust-lang.org/std/io/struct.Error.html#impl-From%3CErrorKind%3E

> Intended for use for errors not exposed to the user, where allocating onto the heap (for normal construction via `Error::new`) is too costly.

**Comment by agerasev** [comment]
Thank you!

You're right, this error message is absolutely unnecessary and could cause a great performance penalty when using this ring buffer as a `Read` or `Write` instance.

I've fixed that and updated the crate.
